### ISSUE TITLE
Python version check breaks on Debian testing

### ISSUE THREAD

**Issue by delroth** [claws/buildbot-prometheus#5]
```
2017-12-28 16:08:02+0000 [-] Traceback (most recent call last):
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/buildbot/plugins/db.py", line 258, in _load_entry
2017-12-28 16:08:02+0000 [-]     result = entry.load()
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
2017-12-28 16:08:02+0000 [-]     return self.resolve()
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
2017-12-28 16:08:02+0000 [-]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/buildbot_prometheus/__init__.py", line 2, in <module>
2017-12-28 16:08:02+0000 [-]     from .prometheus import Prometheus
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/buildbot_prometheus/prometheus.py", line 36, in <module>
2017-12-28 16:08:02+0000 [-]     from prometheus_client import Counter, Gauge, Histogram
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/prometheus_client/__init__.py", line 4, in <module>
2017-12-28 16:08:02+0000 [-]     from . import exposition
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 31, in <module>
2017-12-28 16:08:02+0000 [-]     PYTHON26_OR_OLDER = tuple(int(val) for val in sys.version.split()[0].split('.')) < (2, 7, 0)
2017-12-28 16:08:02+0000 [-]   File "/home/buildbot/venv/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 31, in <genexpr>
2017-12-28 16:08:02+0000 [-]     PYTHON26_OR_OLDER = tuple(int(val) for val in sys.version.split()[0].split('.')) < (2, 7, 0)
2017-12-28 16:08:02+0000 [-] ValueError: invalid literal for int() with base 10: '14+'
```

Debian currently ships with a Python version "2.7.14+", which is arguably stupid but I can't do much about that.

**Comment by delroth** [comment]
Oh, that's in the prometheus_client library, I'm stupid :) Sorry!
